### ISSUE TITLE
As a user I want Georg to be possible to use even if I have some kind of disability.

### ISSUE THREAD

**Issue by lisasund** [Naturhistoriska/Georg#112]
# User story
As a user I want Georg to be possible to use even if I have some kind of disability.

Epic: #107 

# Acceptance criteria

- [ ] The ui is adjusted to accessibility corresponding to this checklist:  https://webbriktlinjer.se/wcag/?checklista ( "Klar" or "Delvis OK" or "Ej relevant" are ok options).

#Tasks
-  [x] Assess accessibility against https://webbriktlinjer.se/wcag/?checklista and note any deviations.
-  [x] Update UI to fix accessibility issues according noted.
-  [x] Test updated features
-  [x] Update checklist answers.
-  [x] Make sure testing against accessability is added to our normal workflows

# Sprint Ready Checklist 
1. - [x] Acceptance criteria defined 
2. - [x] Team understands acceptance criteria 
3. - [x] Team has defined solution / steps to satisfy acceptance criteria 
4. - [x] Acceptance criteria is verifiable / testable 
5. - [x] External / 3rd Party dependencies identified
