### ISSUE TITLE
Search and download data from curated locality lists

### ISSUE THREAD

**Issue by lisasund** [Naturhistoriska/Georg#124]
# Epic 
As a digitiser I want to be able search and download localities from curated lists to get higher quality results from georeferencing.

# Acceptance criteria

- [ ] Metadata should be possible to view and download (e.g. is the list historical, which period, which language)
- [ ] A user can limit results to localities from particular data sources (e.g. only curated data sources or a specific source)
- [ ] It is possible for an administrator of the tool to import data from curated lists with metadata to Georg in some standardised manner
- [ ] ...

# Implementation Ready Checklist 
1. - [ ] Acceptance criteria defined 
2. - [ ] Team understands acceptance criteria 
3. - [ ] User workflows defined / designed 
4. - [ ] Acceptance criteria is verifiable 
5. - [ ] External / 3rd Party dependencies identified

# Workflow / Design 
Define workflow here or add url link to workflow / design document describing it.
